name: Run Java tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Pull MongoDB image
      run: docker pull mongo
    - name: Check docker images
      run: docker images ls
