name: Build application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Pull MongoDB image
      run: docker pull mongo
    - name: Check docker images
      run: docker images ls
    - name: Run MongoDB
      run: docker run -d -p 27017-27019:27017-27019 --name mongodb mongo:4.0.4
    - name: Check running containers
      run: docker ps
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
        run: mvn install

